# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160710_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=255)),
                ('Eligibility', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
