# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_commerce'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegepages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('fan_count', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='keyword_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('page_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=255)),
                ('Eligibility', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
