# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_twitter_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='humanity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=255)),
                ('Eligibility', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='collegepages',
            name='page_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collegepages',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collegeposts',
            name='created_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collegeposts',
            name='page_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='collegeposts',
            name='post_id',
            field=models.CharField(max_length=255),
        ),
    ]
