# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160711_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('created_time', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='collegeposts',
            name='page_id',
            field=models.CharField(max_length=255),
        ),
    ]
