# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160711_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegepages_commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('fan_count', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='collegepages_humanity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('fan_count', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='collegeposts_commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('created_time', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='collegeposts_humanity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('created_time', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
